module.exports = {
  ...require('./actionService'),
  ...require('./buildService'),
  ...require('./composeService'),
  ...require('./destroyService'),
  ...require('./getServiceArgs'),
  ...require('./mutagenService'),
  ...require('./packageService'),
  ...require('./restartService'),
  ...require('./serviceOptions'),
  ...require('./startService'),
  ...require('./stopService'),
  ...require('./syncService'),
  ...require('./syncActionService'),
  ...require('./runService'),
}