#!/usr/bin/env node

require('module-alias/register')

;(async () => {
  try {

    const { loadGlobalConfig } = require('KegUtils/globalConfig/loadGlobalConfig')
    const { checkUpdates } = require('KegScripts/cli/checkUpdates')
    const { getSetting } = require('KegUtils/globalConfig/getSetting')

    // Load the users global config, or create it on the fly
    const globalConfig = await loadGlobalConfig()

    // Pull in the runTask method, and call it immediately
    const { runTask } = require('KegRunTask')
    await runTask(globalConfig)

    // Check for Keg CLI updates if setting is true
    getSetting('checkUpdates') && await checkUpdates()

  }
  catch(e){
    console.error(e.stack)
  }

})()
