#!/usr/bin/env node

require('module-alias/register')
const { getGlobalConfig } = require('KegUtils/globalConfig/getGlobalConfig')
const { runTask } = require('KegRunTask')

;(() => {
  try {

    // Load the users global config, or create it on the fly
    // Pull in the runTask method, and call it immediately
    return runTask(getGlobalConfig())
  }
  catch(e){
    console.error(e.stack)
  }

})()