version: "3.8"
services:
  keg-core:
    # TODO: Define the KEG_FROM_IMAGE
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - KEG_BASE_IMAGE
        - KEG_NODE_VERSION
    environment:
      - CHOKIDAR_USEPOLLING
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RESOLVER_PATH
      - DOC_RETHEME_PATH
      - DOC_JSUTILS_PATH
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_IMAGE_FROM
      - KEG_NM_INSTALL
      - NODE_ENV
