version: "3.8"
networks:
  keg-hub-net:
    external: true
services:
  {{ image }}:
    image: {{ image }}
    container_name: {{ container }}
    tty: true
    stdin_open: true
    networks:
      - keg-hub-net
    build:
      context: {{ buildContextPath }}
      dockerfile: {{ dockerPath }}
    labels:
{{ generatedLabels }}