version: "3.8"
services:
  {{ image }}:
    image: {{ image }}
    container_name: {{ container }}
    tty: true
    stdin_open: true
    build:
      context: {{ injectPath }}
      dockerfile: {{ dockerPath }}
    labels:
{{ generatedLabels }}