// ******** IMPORTANT ********
// DO NOT EDIT THIS FILE
// Any metro config changes should be done at <root>/core/configs/metro.config.js
module.exports = require('./core/configs/metro.config')(__dirname)
// DO NOT EDIT THIS FILE
// ******** IMPORTANT ********
