// ******** IMPORTANT ********
// DO NOT EDIT THIS FILE
// Any webpack config changes should be done at <root>/core/configs/webpack.config.js
module.exports = require('./core/configs/webpack.config')(__dirname)
// DO NOT EDIT THIS FILE
// ******** IMPORTANT ********
