env:

  # --- KEG-CLI ENV CONTEXT --- #

  # Set the paths to the linked external app
  # The app should be linked to the keg-cli with `kee`
  # Example command to link the app => `keg tap link kee`
  KEG_DOCKER_FILE: "{{ cli.taps.links.rc }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.links.rc }}/container/values.yml"
  KEG_COMPOSE_DEFAULT: "{{ cli.taps.links.rc }}/container/docker-compose.yml"

  # The KEG_CONTEXT_PATH env should be the location of the external app being run
  KEG_CONTEXT_PATH: "{{ cli.taps.links.rc }}"

  # --- DOCKER ENV CONTEXT --- #

  # Default location of the app in the docker container
  DOC_APP_PATH: /keg/tap
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_COMPONENTS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
  DOC_RETHEME_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
  DOC_RESOLVER_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/tap-resolver

  # Default port of the app to expose from the container
  DOC_APP_PORT: 19006

  # --- GENERAL CONTEXT ENVs --- #

  # Image/Container Build information
  # IMAGE and CONTAINER_NAME should be the same
  IMAGE: rc
  CONTAINER_NAME: rc
  VERSION: "0.0.1"
