version: "3.8"
services:
  keg-proxy:
    image: traefik:v2.2
    tty: true
    stdin_open: true
    privileged: true
    networks:
      - keg-hub-net
    container_name: keg-proxy
    command:
      - --log.level=${PROXY_LOG_LEVEL:-ERROR}
      - --api.insecure=${PROXY_INSECURE:-true}
      - --providers.docker
      - --providers.docker.exposedbydefault=${PROXY_EXPOSED:-true}
      - --entrypoints.keg.address=:${PROXY_KEG_ENTRY:-80}
    ports:
      - ${PROXY_INSECURE_PORT}:${PROXY_INSECURE_PORT:-80}
      - ${PROXY_SECURE_PORT}:${PROXY_SECURE_PORT:-443}
      - ${PROXY_DASHBOARD_PORT}:${PROXY_DASHBOARD_PORT:-8080}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    keg-hub-net:
        driver: bridge
        name: keg-hub-net