version: "3.8"
services:
  keg-proxy:
    image: traefik:v2.2
    tty: true
    stdin_open: true
    privileged: true
    networks:
      - ${KEG_DOCKER_NETWORK}
    container_name: keg-proxy
    command:
      - --log.level=${PROXY_LOG_LEVEL:-ERROR}
      # TODO: update to turn this off for production environment
      - --api=true
      - --api.insecure=${PROXY_INSECURE:-true}
      - --providers.docker
      # Set the default network, but can be overridden at the container level with a `traefik.docker.network` label
      - --providers.docker.network=${KEG_DOCKER_NETWORK}
      # If this is set to false, the containers must have the label "traefik.enable=true"
      # We may want to switch to this to allow dynamically exposing containers based on environment
      - --providers.docker.exposedbydefault=${PROXY_EXPOSED:-true}
      - --entrypoints.${KEG_PROXY_ENTRY}.address=:${PROXY_ENTRY_PORT:-80}
    labels:
      # These labels will route traffic at the root host to the traefik dashboard
      # All other docker containers use a sub-domain
      - traefik.http.routers.api.rule=Host(`${KEG_PROXY_HOST}`)
      - traefik.http.routers.api.service=api@internal
    ports:
      - ${PROXY_INSECURE_PORT}:${PROXY_INSECURE_PORT:-80}
      - ${PROXY_SECURE_PORT}:${PROXY_SECURE_PORT:-443}
      - ${PROXY_DASHBOARD_PORT}:${PROXY_DASHBOARD_PORT:-18001}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    keg-hub-net:
        driver: bridge
        name: keg-hub-net