
env:
  # --- LOCAL ENV CONTEXT --- #

  KEG_DOCKER_FILE: "{{ cli.paths.containers }}/proxy/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.paths.containers }}/proxy/values.yml"
  KEG_COMPOSE_DEFAULT: "{{ cli.paths.containers }}/proxy/docker-compose.yml"

  # Turn off adding an injected compose config for keg-proxy
  KEG_NO_INJECTED_COMPOSE: true

  # Turn off auto-building the keg-base image
  KEG_FROM_BASE: false

  # Turn off auto-creating a keg-proxy sync
  KEG_AUTO_SYNC: false

  # Default host for the keg proxy
  KEG_PROXY_HOST: local.kegdev.xyz

  # Proxy port testing to be exposed by docker
  PROXY_INSECURE_PORT: 80
  PROXY_SECURE_PORT: 443
  PROXY_DASHBOARD_PORT: 18001

  # Defualt proxy settings
  PROXY_INSECURE: true
  PROXY_EXPOSED: true

  # Must be one of DEBUG, PANIC, FATAL, ERROR, WARN, INFO
  PROXY_LOG_LEVEL: ERROR

  # Entry port for trafik to route to keg containers
  PROXY_ENTRY_PORT: 80
