
name: keg-build
on:
  push:
    branches:
      - ZEN-543-rebuild-workflow
      - develop

jobs:
  build-images:
    name: 'Build Images'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CLI_BRANCH: ZEN-543-updates-for-workflow
      CLI_PATH: ${{env.GITHUB_WORKSPACE}}/keg-cli
      CLI_USER: keg-admin
      GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
      KEG_GLOBAL_CONFIG: ${{env.CLI_PATH}}/.kegConfig/cli.config.json
      HUB_BRANCH: ${GITHUB_REF##*/}
    steps:
    - name: "Clone Keg-CLI"
      id: clone-cli
      run: git -C $GITHUB_WORKSPACE clone --single-branch --branch ${{env.CLI_BRANCH}} https://github.com/simpleviewinc/keg-cli.git
    - name: "Install Keg-CLI"
      id: install-cli
      run: yarn --cwd $GITHUB_WORKSPACE/keg-cli install
    - name: "Setup Keg-CLI"
      id: setup-cli
      run: cd $GITHUB_WORKSPACE/keg-cli; USER=${{env.CLI_USER}} KEG_HUB_BRANCH=${{env.HUB_BRANCH}} KEG_ROOT_DIR=$GITHUB_WORKSPACE/keg-hub bash scripts/ci/setupCLIConfig.sh
    - name: "Set Git Key"
      id: set-git-key
      run: source $GITHUB_WORKSPACE/keg-cli/keg && keg git key add --value ${{env.GIT_TOKEN}} --confirm false
    - name: "Set Git Username"
      id: set-git-user
      run: git config --global user.name ${{env.CLI_USER}}
    - name: "Docker Login"
      id: docker-login
      run: source $GITHUB_WORKSPACE/keg-cli/keg && keg dp login
    - name: "Link Taps"
      id: link-taps
      run: cd $GITHUB_WORKSPACE/keg-hub && node scripts/ci/linkTaps.js
    - name: "Build and Push"
      id: build-push-images
      run: cd $GITHUB_WORKSPACE/keg-hub && GIT_KEY=${{env.GIT_TOKEN}} bash scripts/ci/buildPushDockerImages.sh
