
name: keg-docker-image
on: push
# on:
#   push:
#     branches:
#       - develop

jobs:
  build:
    name: 'Build Docker Keg Images'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Setup node Version"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "Setup Keg-CLI"
        id: setup-keg-cli
        run: bash scripts/ci/setupKegCLI.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: "Build keg-hub docker images"
        id: build-docker-images
        run: bash scripts/ci/buildImages.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
