
name: keg-build-images
on:
  push:
    branches:
      - ZEN-543-rebuild-workflow
      - develop

jobs:
  build-images:
    name: 'Build Images'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KEG_CLI_BRANCH: ZEN-543-updates-for-workflow
      KEG_CLI_PATH: ${{ github.workspace }}/keg-cli
      KEG_CLI_USER: keg-admin
      KEG_GLOBAL_CONFIG: ${{ github.workspace }}/keg-cli/.kegConfig/cli.config.json
      KEG_HUB_PATH: ${{ github.workspace }}/keg-hub
    steps:
      - name: "Clone Keg-CLI"
        id: clone-cli
        run: git -C $GITHUB_WORKSPACE clone --single-branch --branch ${{env.KEG_CLI_BRANCH}} https://github.com/simpleviewinc/keg-cli.git

      - name: "Setup Keg Environment"
        id: setup-environment
        run: cd $GITHUB_WORKSPACE/keg-cli && KEG_HUB_BRANCH=${GITHUB_REF##*/} bash scripts/ci/setupKegEnvironment.sh
        env:
          KEG_ROOT_DIR: ${{ env.KEG_HUB_PATH }}
          KEG_CLI_BRANCH: ZEN-543-updates-for-workflow
          KEG_CLI_USER: keg-admin

      - name: "Link Keg-Hub Taps"
        id: link-taps
        run: cd $KEG_HUB_PATH && node scripts/ci/linkTaps.js

      - name: "Build and Push"
        id: build-push-images
        run: cd $KEG_HUB_PATH && bash scripts/ci/buildPushDockerImages.sh
